version: '3'
services:
  product_service:
    container_name: "product_service"
    build:
      context: ./nab-product-service
    environment:
      ENV: "development"
      PORT: 3000
      DB_NAME: ${PRODUCT_DATABASE_NAME}
      DB_USERNAME: 'root'
      DB_PASSWORD: ${PRODUCT_DATABASE_PASSWORD}
      DB_HOST: product_db #use container_name refer to host
      AMQP_URL: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@message_queue #use container_name refer to host
      AMQP_USER_ACTIVITY_QUEUE: ${ACTIVITY_QUEUE}
    networks:
      - product_network
      - communicate_network
    ports:
      - "3000:3000"
    depends_on:
      - product_db
      - message_queue
    links:
      - product_db
  product_db:
    container_name: "product_db"
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PRODUCT_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${PRODUCT_DATABASE_NAME}
    networks:
      - product_network
  message_queue:
    container_name: "message_queue"
    image: "bitnami/rabbitmq"
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    networks:
      - communicate_network
  activity_service:
    container_name: "activity_service"
    build:
      context: ./nab-activity-service
    environment:
      ENV: "development"
      PORT: 3001
      DB_NAME: ${ACTIVITY_DATABASE_NAME}
      DB_USERNAME: ${ACTIVITY_DATABASE_USERNAME}
      DB_PASSWORD: ${ACTIVITY_DATABASE_PASSWORD}
      DB_HOST: activity_db  #use container_name refer to host
      AMQP_URL: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@message_queue  #use container_name refer to host
      AMQP_USER_ACTIVITY_QUEUE: ${ACTIVITY_QUEUE}
    networks:
      - activity_network
      - communicate_network
    depends_on:
      - activity_db
      - message_queue
    links:
      - activity_db
  activity_db:
    image: "mongo:latest"
    networks:
      - activity_network
    restart: always
    ports:
    - "4000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ACTIVITY_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ACTIVITY_DATABASE_PASSWORD}
networks:
  product_network:
    driver: bridge
  activity_network:
    driver: bridge
  communicate_network:
    driver: bridge